complete -c aider

# Main model options
complete -c aider -l model -a "(aider --list-models all | cut -d ' ' -f2-)" -d "Specify the model to use for the main chat"
complete -c aider -l opus -d "Use claude-3-opus-20240229 model"
complete -c aider -l sonnet -d "Use claude-3-5-sonnet-20241022 model"
complete -c aider -l haiku -d "Use claude-3-5-haiku-20241022 model"
complete -c aider -s 4 -l 4 -d "Use gpt-4-0613 model"
complete -c aider -l 4o -d "Use gpt-4o model"
complete -c aider -l mini -d "Use gpt-4o-mini model"
complete -c aider -l 4-turbo -d "Use gpt-4-1106-preview model"
complete -c aider -l 35turbo -l 35-turbo -s 3 -l 3 -d "Use gpt-3.5-turbo model"
complete -c aider -l deepseek -d "Use deepseek/deepseek-coder model"
complete -c aider -l o1-mini -d "Use o1-mini model"
complete -c aider -l o1-preview -d "Use o1-preview model"

# API Keys and settings
complete -c aider -l openai-api-key -d "Specify the OpenAI API key"
complete -c aider -l anthropic-api-key -d "Specify the Anthropic API key"
complete -c aider -l openai-api-base -d "Specify the api base url"
complete -c aider -l openai-api-type -d "(deprecated) Specify the OpenAI API type"
complete -c aider -l openai-api-version -d "(deprecated) Specify the OpenAI API version"
complete -c aider -l openai-api-deployment-id -d "(deprecated) Specify the OpenAI API deployment ID"
complete -c aider -l openai-organization-id -d "(deprecated) Specify the OpenAI organization ID"
complete -c aider -l set-env -r -d "Set an environment variable (e.g., OPENAI_API_TYPE=azure)"
complete -c aider -l api-key -r -d "Set an API key for a provider (e.g., provider=key)"

# Model settings
complete -c aider -l list-models -l models -d "List known models"
complete -c aider -l model-settings-file -a "*.yml *.yaml" -d "Specify a file with aider model settings"
complete -c aider -l model-metadata-file -a "*.yml *.yaml" -d "Specify a file with context window and costs for unknown models"
complete -c aider -l alias -r -d "Add a model alias (e.g., mymodel:gpt-4)"
complete -c aider -l verify-ssl -d "Verify SSL certs"
complete -c aider -l no-verify-ssl -d "Do not verify SSL certs"
complete -c aider -l timeout -r -d "Timeout in seconds for API calls"
complete -c aider -l edit-format -l chat-mode -a "diff unified patch" -d "Specify the edit format"
complete -c aider -l architect -d "Use architect edit format"
complete -c aider -l weak-model -d "Model for commit messages and chat history summarization"
complete -c aider -l editor-model -d "Model for editor tasks"
complete -c aider -l editor-edit-format -a "diff unified patch" -d "Edit format for editor model"
complete -c aider -l show-model-warnings -d "Show model warnings"
complete -c aider -l no-show-model-warnings -d "Do not show model warnings"
complete -c aider -l max-chat-history-tokens -r -d "Soft limit on tokens for chat history"

# Cache settings
complete -c aider -l cache-prompts -d "Enable caching of prompts"
complete -c aider -l no-cache-prompts -d "Disable caching of prompts"
complete -c aider -l cache-keepalive-pings -r -d "Number of times to ping to keep prompt cache warm"

# Repomap settings
complete -c aider -l map-tokens -r -d "Suggested number of tokens for repo map"
complete -c aider -l map-refresh -a "auto always files manual" -d "Control how often the repo map is refreshed"
complete -c aider -l map-multiplier-no-files -r -d "Multiplier for map tokens when no files are specified"

# History Files
complete -c aider -l input-history-file -a "*.history" -d "Specify the chat input history file"
complete -c aider -l chat-history-file -a "*.md" -d "Specify the chat history file"
complete -c aider -l restore-chat-history -d "Restore previous chat history"
complete -c aider -l no-restore-chat-history -d "Do not restore previous chat history"
complete -c aider -l llm-history-file -a "*.history" -d "Log the conversation with the LLM"

# Output settings
complete -c aider -l dark-mode -d "Use colors suitable for a dark terminal"
complete -c aider -l light-mode -d "Use colors suitable for a light terminal"
complete -c aider -l pretty -d "Enable pretty output"
complete -c aider -l no-pretty -d "Disable pretty output"
complete -c aider -l stream -d "Enable streaming responses"
complete -c aider -l no-stream -d "Disable streaming responses"
complete -c aider -l user-input-color -d "Set the color for user input"
complete -c aider -l tool-output-color -d "Set the color for tool output"
complete -c aider -l tool-error-color -d "Set the color for tool error messages"
complete -c aider -l tool-warning-color -d "Set the color for tool warning messages"
complete -c aider -l assistant-output-color -d "Set the color for assistant output"
complete -c aider -l completion-menu-color -d "Set the color for the completion menu"
complete -c aider -l completion-menu-bg-color -d "Set the background color for the completion menu"
complete -c aider -l completion-menu-current-color -d "Set the color for the current item in the completion menu"
complete -c aider -l completion-menu-current-bg-color -d "Set the background color for the current item in the completion menu"
complete -c aider -l code-theme -d "Set the markdown code theme"
complete -c aider -l show-diffs -d "Show diffs when committing"

# Git settings
complete -c aider -l git -d "Enable git repo lookup"
complete -c aider -l no-git -d "Disable git repo lookup"
complete -c aider -l gitignore -d "Add .aider* to .gitignore"
complete -c aider -l no-gitignore -d "Do not add .aider* to .gitignore"
complete -c aider -l aiderignore -a "*.aiderignore" -d "Specify the aider ignore file"
complete -c aider -l subtree-only -d "Only consider files in the current subtree"
complete -c aider -l auto-commits -d "Enable auto commit of LLM changes"
complete -c aider -l no-auto-commits -d "Disable auto commit of LLM changes"
complete -c aider -l dirty-commits -d "Enable commits when repo is dirty"
complete -c aider -l no-dirty-commits -d "Disable commits when repo is dirty"
complete -c aider -l attribute-author -d "Attribute aider code changes in git author name"
complete -c aider -l no-attribute-author -d "Do not attribute aider code changes in git author name"
complete -c aider -l attribute-committer -d "Attribute aider commits in git committer name"
complete -c aider -l no-attribute-committer -d "Do not attribute aider commits in git committer name"
complete -c aider -l attribute-commit-message-author -d "Prefix commit messages with 'aider: ' if aider authored"
complete -c aider -l no-attribute-commit-message-author -d "Do not prefix commit messages with 'aider: ' if aider authored"
complete -c aider -l attribute-commit-message-committer -d "Prefix all commit messages with 'aider: '"
complete -c aider -l no-attribute-commit-message-committer -d "Do not prefix all commit messages with 'aider: '"
# Git settings (continued)
complete -c aider -l commit -d "Commit all pending changes"
complete -c aider -l commit-prompt -r -d "Specify a custom prompt for commit messages"
complete -c aider -l dry-run -d "Perform a dry run"
complete -c aider -l no-dry-run -d "Do not perform a dry run"
complete -c aider -l skip-sanity-check-repo -d "Skip the sanity check for the git repo"
complete -c aider -l watch-files -d "Enable watching files for ai coding comments"
complete -c aider -l no-watch-files -d "Disable watching files for ai coding comments"

# Fixing and committing
complete -c aider -l lint -d "Lint and fix provided files"
complete -c aider -l lint-cmd -r -d "Specify lint commands (e.g., python:flake8)"
complete -c aider -l auto-lint -d "Enable automatic linting"
complete -c aider -l no-auto-lint -d "Disable automatic linting"
complete -c aider -l test-cmd -r -d "Specify command to run tests"
complete -c aider -l auto-test -d "Enable automatic testing"
complete -c aider -l no-auto-test -d "Disable automatic testing"
complete -c aider -l test -d "Run tests, fix problems, then exit"

# Analytics
complete -c aider -l analytics -d "Enable analytics"
complete -c aider -l no-analytics -d "Disable analytics"
complete -c aider -l analytics-log -a "*.log" -d "Specify a file to log analytics events"
complete -c aider -l analytics-disable -d "Permanently disable analytics"

# Upgrading
complete -c aider -l just-check-update -d "Check for updates and return status"
complete -c aider -l check-update -d "Check for new aider versions on launch"
complete -c aider -l no-check-update -d "Do not check for new aider versions on launch"
complete -c aider -l show-release-notes -d "Show release notes on first run of new version"
complete -c aider -l no-show-release-notes -d "Do not show release notes on first run of new version"
complete -c aider -l install-main-branch -d "Install from the main branch"
complete -c aider -l upgrade -l update -d "Upgrade aider to the latest version"

# Modes
complete -c aider -l message -l msg -s m -r -d "Specify a message to send the LLM"
complete -c aider -l message-file -s f -a "*.txt" -d "Specify a file containing the message"
complete -c aider -l gui -l browser -d "Run aider in your browser"
complete -c aider -l no-gui -l no-browser -d "Do not run aider in your browser"
complete -c aider -l copy-paste -d "Enable automatic copy/paste with web UI"
complete -c aider -l no-copy-paste -d "Disable automatic copy/paste with web UI"
complete -c aider -l apply -a "*" -d "Apply changes from a file (debug)"
complete -c aider -l apply-clipboard-edits -d "Apply clipboard edits (debug)"
complete -c aider -l exit -d "Exit after startup (debug)"
complete -c aider -l show-repo-map -d "Print the repo map (debug)"
complete -c aider -l show-prompts -d "Print system prompts (debug)"

# Voice settings
complete -c aider -l voice-format -a "wav webm mp3" -d "Audio format for voice recording"
complete -c aider -l voice-language -d "Language for voice (ISO 639-1 code)"
complete -c aider -l voice-input-device -d "Input device for voice recording"

# Other settings
complete -c aider -l file -a "*" -d "Specify a file to edit"
complete -c aider -l read -a "*" -d "Specify a read-only file"
complete -c aider -l vim -d "Use VI editing mode"
complete -c aider -l chat-language -d "Language to use in the chat"
complete -c aider -l yes-always -d "Always say yes to confirmations"
complete -c aider -l verbose -d "Enable verbose output"
complete -c aider -l load -a "*.cmds" -d "Load and execute commands from a file"
complete -c aider -l encoding -d "Specify the encoding"
complete -c aider -l config -s c -a "*.yml *.yaml" -d "Specify the config file"
complete -c aider -l env-file -a ".env" -d "Specify the .env file"
complete -c aider -l suggest-shell-commands -d "Enable suggesting shell commands"
complete -c aider -l no-suggest-shell-commands -d "Disable suggesting shell commands"
complete -c aider -l fancy-input -d "Enable fancy input"
complete -c aider -l no-fancy-input -d "Disable fancy input"
complete -c aider -l multiline -d "Enable multi-line input mode"
complete -c aider -l no-multiline -d "Disable multi-line input mode"
complete -c aider -l detect-urls -d "Enable URL detection in chat"
complete -c aider -l no-detect-urls -d "Disable URL detection in chat"
complete -c aider -l editor -d "Specify which editor to use for /editor"


